import type { Metadata } from "next";
import "./globals.css";
// import { Inter } from "next/font/google"
import localFont from 'next/font/local'
import { ReduxProvider } from './_components/ReduxProvider';

// export const metadata: Metadata = {
//   title: "FashionStore",
//   description: "Generated by create next app",
// };

// const inter = Inter({ subsets: ['latin'] })

// const MyFont = localFont({
//   src: [
//     {
//       path: 'app/fonts/RFDewi/RFDewi-Bold.woff2',
//       weight: '700',
//       style: 'normal'
//     },
//     {
//       path: 'app/fonts/RFDewi/RFDewi-Semibold.woff2',
//       weight: '600',
//       style: 'normal'
//     },
//     {
//       path: 'app/fonts/RFDewi/RFDewi-Black.woff2',
//       weight: '900',
//       style: 'normal'
//     },
//     {
//       path: 'app/fonts/RFDewi/RFDewi-Ultrabold.woff2',
//       weight: '800',
//       style: 'normal'
//     },
//   ]
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white`}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
